from tkinter import *
from tkinter import messagebox
from tkinter import ttk
import sys
import tkinter as tk
import os
#from tkinter import config
from tkinter import Tk, Frame, Menu
import sqlite3
window = Tk()
#=========================================================================================================
tab_control = ttk.Notebook(window,width='1200',height='2000')
tab_control.place(x=150,y=10)

tab1 = ttk.Frame(tab_control)
tab2 = ttk.Frame(tab_control)
tab3 = ttk.Frame(tab_control)
tab4 = ttk.Frame(tab_control)
tab5 = ttk.Frame(tab_control)
tab6 = ttk.Frame(tab_control)

line1=tab_control.add(tab1, text='Home                                    ')
line1=Frame(tab1,bg='light green', width=2050, height=1000) 
line1.place(x=1, y=10)
line2=tab_control.add(tab2, text='About Us                    ')
line2=Frame(tab2,bg='light blue', width=2050, height=1000) 
line2.place(x=1, y=10)
line3=tab_control.add(tab3, text='Services Available                                 ')
line3=Frame(tab3,bg='light blue', width=2050, height=1000) 
line3.place(x=1, y=10)
line4=tab_control.add(tab4, text='Room Services                            ')
line4=Frame(tab4,bg='light blue', width=2050, height=1000) 
line4.place(x=1, y=10)
line5=tab_control.add(tab5, text='Restuarant Services                                 ')
line5=Frame(tab5,bg='light blue', width=2050, height=1000) 
line5.place(x=1, y=10)
line6=tab_control.add(tab6, text='Booking                          ')
line6=Frame(tab6,bg='light blue', width=2050, height=1000) 
line6.place(x=1, y=10)
#====================================================================tab 1 start===================================
start1=Label(tab1,text='WELCOME TO SKYLITE HOTEL!!',width="30",height=1,bg="light blue",fg="purple",font=("lucida calligraphy",30))
start1.place(x=100,y=30)

imagehome=PhotoImage(file="image8.png")
Ftab1=Label(tab1,image=imagehome)
Ftab1.place(x=100,y=100)

#=======================================tab2 start===============================================================
start2=Label(tab2,text='Welcome to Skylite Hotel \nThe ultimate place for you and your loved ones,\n come relax and have fun out of home',bg="light blue",font=("lucida calligraphy",20))
start2.place(x=100,y=10)

image2home=PhotoImage(file="image7.png")
Ftab2=Label(tab2,image=image2home)
Ftab2.place(x=100,y=120)

Htab2= Label(tab2, text="Location:",  fg='darkblue',bg="white", font=('lucida calligraphy', 14))
Htab2.place(x=100, y=530)
Htab2 = Label(tab2, text="Skylite Hotel is located opposite Centinary Bank Main Branch in Kampala",  fg='darkblue',bg="white", font=('lucida calligraphy', 12))
Htab2.place(x=250, y=530)



Htab2= Label(tab2, text="Contact Us On:",  fg='darkblue',bg="white", font=('times new roman', 14))
Htab2.place(x=100, y=610)
Htab2 = Label(tab2, text="+256 756522695", fg='black',bg="white", font=('times new roman', 12))
Htab2.place(x=225, y=610)
Htab2= Label(tab2, text="+256 786813872", fg='black',bg="white", font=('times new roman', 12))
Htab2.place(x=225, y=640)

Htab2 = Label(tab2, text="E-mail:",  fg='darkblue',bg="white", font=('times new roman', 14))
Htab2.place(x=350, y=610)

Htab2 = Label(tab2, text="skylitehotel.org.ug",  fg='black',bg="white", font=('times new roman', 12))
Htab2.place(x=420, y=610)

Htab2 =Label(tab2,text="skylitehotel@gmail.com",fg='black',bg="white",font=('times new roman',12))
Htab2.place(x=420, y=640)

Htab2 = Label(tab2, text="Media:",  fg='darkblue',bg="white", font=('times new roman', 14))
Htab2.place(x=620, y=610)

Htab2 = Label(tab2, text="YouTube",  fg='black',bg="white", font=('times new roman', 12))
Htab2.place(x=680, y=640)
Htab2= Label(tab2,text="Twitter  @skylitehotel",  fg='black',bg="white", font=('times new roman', 12))
Htab2.place(x=750, y=610)
Htab2 = Label(tab2,text="Instagram @skylitehotel",  fg='black',bg="white", font=('times new roman', 12))
Htab2.place(x=750, y=640)
imagelhome=PhotoImage(file="log.png")
Ltab2=Label(tab2,image=imagelhome)
Ltab2.place(x=920,y=520)

start3=Label(tab3,text='Services Available',bg="light blue",font=("lucida calligraphy",20))
start3.place(x=400,y=10)
Jtab3=Label(tab3,text='Room Services',font=('calbri 17 bold'),bg='light blue',fg='black',width=20)
Jtab3.place(x=90,y=50)
image5home=PhotoImage(file="room 1.png")
Jtab3=Label(tab3,image=image5home)
Jtab3.place(x=10,y=80)
image4home=PhotoImage(file="room1.png")
Jtab3=Label(tab3,image=image4home)
Jtab3.place(x=10,y=270)
image6home=PhotoImage(file="Rm1.png")
Jtab3=Label(tab3,image=image6home)
Jtab3.place(x=10,y=448)
image7home=PhotoImage(file="rm9.png")
Jtab3=Label(tab3,image=image7home)
Jtab3.place(x=285,y=80)
image8home=PhotoImage(file="rm8.png")
Jtab3=Label(tab3,image=image8home)
Jtab3.place(x=285,y=266)
image9home=PhotoImage(file="rm10.png")
Jtab3=Label(tab3,image=image9home)
Jtab3.place(x=285,y=448)

Jtab3=Label(tab3,text=' Restuarant Services',font=('calbri 15 bold'),bg='light blue',fg='black',width=20)
Jtab3.place(x=700,y=50)
image10home=PhotoImage(file="food1.png")
Jtab3=Label(tab3,image=image10home)
Jtab3.place(x=670,y=80)
image11home=PhotoImage(file="food2.png")
Jtab3=Label(tab3,image=image11home)
Jtab3.place(x=670,y=250)
image12home=PhotoImage(file="food5.png")
Jtab3=Label(tab3,image=image12home)
Jtab3.place(x=930,y=80)
image13home=PhotoImage(file="food4.png")
Jtab3=Label(tab3,image=image13home)
Jtab3.place(x=940,y=250)
image14home=PhotoImage(file="food3.png")
Jtab3=Label(tab3,image=image14home)
Jtab3.place(x=670,y=430)
image15home=PhotoImage(file="fd6.png")
Jtab3=Label(tab3,image=image15home)
Jtab3.place(x=930,y=440)
#=================================================single==================================
Mtab4=Label(tab4,text='Room Category',font=('calbri 15 bold'),bg='light blue',fg='black',width=20)
Mtab4.place(x=10,y=20)
Mtab4=Label(tab4,text='Single',font=('calbri 15 bold '),bg='light blue',fg='red',width=20)
Mtab4.place(x=10,y=60)
Mtab4=Label(tab4,text='No.1',font=('calbri 15 bold '),bg='light blue',fg='red',width=20)
Mtab4.place(x=20,y=90)
Mtab4=Label(tab4,text='No.2',font=('calbri 15 bold '),bg='light blue',fg='red',width=20)
Mtab4.place(x=310,y=90)
Mtab4=Label(tab4,text='No.3',font=('calbri 15 bold '),bg='light blue',fg='red',width=20)
Mtab4.place(x=600,y=90)
Mtab4=Label(tab4,text='No.4',font=('calbri 15 bold '),bg='light blue',fg='red',width=20)
Mtab4.place(x=840,y=90)
Mtab4=Label(tab4,text='Price @day',font=('calbri 15 bold'),bg='light blue',fg='black',width=20)
Mtab4.place(x=700,y=20)
Mtab4=Label(tab4,text='50,000Ugx',font=('calbri 15 bold '),bg='light blue',fg='red',width=20)
Mtab4.place(x=700,y=60)
image16home=PhotoImage(file="Rm1.png")
Jtab4=Label(tab4,image=image16home)
Jtab4.place(x=20,y=120)
image17home=PhotoImage(file="Rm2.png")
Jtab4=Label(tab4,image=image17home)
Jtab4.place(x=310,y=120)
image1home=PhotoImage(file="Rm3.png")
Jtab4=Label(tab4,image=image1home)
Jtab4.place(x=600,y=120)
image18home=PhotoImage(file="Rmm.png")
Jtab4=Label(tab4,image=image18home)
Jtab4.place(x=840,y=120)
#=================================================double==========================================
Mtab4=Label(tab4,text='Room Category',font=('calbri 15 bold'),bg='light blue',fg='black',width=20)
Mtab4.place(x=10,y=300)
Mtab4=Label(tab4,text='Double',font=('calbri 15 bold '),bg='light blue',fg='red',width=20)
Mtab4.place(x=10,y=330)
Mtab4=Label(tab4,text='Price @day',font=('calbri 15 bold'),bg='light blue',fg='black',width=20)
Mtab4.place(x=700,y=300)
Mtab4=Label(tab4,text='100,000Ugx',font=('calbri 15 bold '),bg='light blue',fg='red',width=20)
Mtab4.place(x=700,y=330)
Mtab4=Label(tab4,text='No.5',font=('calbri 15 bold '),bg='light blue',fg='red',width=20)
Mtab4.place(x=20,y=360)
Mtab4=Label(tab4,text='No.6',font=('calbri 15 bold '),bg='light blue',fg='red',width=20)
Mtab4.place(x=310,y=360)
Mtab4=Label(tab4,text='No.7',font=('calbri 15 bold '),bg='light blue',fg='red',width=20)
Mtab4.place(x=600,y=360)
Mtab4=Label(tab4,text='No.8',font=('calbri 15 bold '),bg='light blue',fg='red',width=20)
Mtab4.place(x=840,y=360)
image20home=PhotoImage(file="db1.png")
Jtab4=Label(tab4,image=image20home)
Jtab4.place(x=20,y=390)
image21home=PhotoImage(file="db2.png")
Jtab4=Label(tab4,image=image21home)
Jtab4.place(x=300,y=390)
image22home=PhotoImage(file="db3.png")
Jtab4=Label(tab4,image=image22home)
Jtab4.place(x=590,y=390)
image23home=PhotoImage(file="db4.png")
Jtab4=Label(tab4,image=image23home)
Jtab4.place(x=865,y=390)

def HOTEL_MANAGEMENT():
    root.destroy()

    import mainly
    a=mainly.HOTEL_MANAGEMENT()
    tab6()





mainloop()
